version: '3.8'

services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: orbstack-monitor
    ports:
      - 19999:19999
    restart: unless-stopped
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=${NETDATA_CLAIM_URL}
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS}
    volumes:
      # Persistent storage for configuration and data
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      # Full root filesystem access for comprehensive monitoring
      - /:/host/root:ro,rslave
      # System monitoring
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/localtime:/etc/localtime:ro
      # Docker monitoring - essential for container auto-discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # DBus for additional system monitoring
      - /run/dbus:/run/dbus:ro
      # Logs monitoring (optional but useful)
      - /var/log:/host/var/log:ro

volumes:
  netdataconfig:
  netdatalib:
  netdatacache: